/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.1.12 public/models/base.glb
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/base.glb')
  return (
    <group {...props} dispose={null}>
      <group position={[0, 0.36, -0.01]} rotation={[0, -Math.PI / 2, 0]} scale={0.01}>
        <primitive object={nodes.Bip001_Pelvis} />
        <skinnedMesh geometry={nodes.body.geometry} material={materials['chars_body01.001']} skeleton={nodes.body.skeleton} />
        <skinnedMesh geometry={nodes.body_Accessory.geometry} material={materials['bag02.001']} skeleton={nodes.body_Accessory.skeleton} />
        <skinnedMesh geometry={nodes.bottom_cloth.geometry} material={materials['chars_pnats04.001']} skeleton={nodes.bottom_cloth.skeleton} />
        <skinnedMesh geometry={nodes.cloth.geometry} material={materials['chars_cloth08.001']} skeleton={nodes.cloth.skeleton} />
        <skinnedMesh geometry={nodes.eyeballL.geometry} material={materials['chars_eyeball01.001']} skeleton={nodes.eyeballL.skeleton} />
        <skinnedMesh geometry={nodes.eyeballR.geometry} material={materials['chars_eyeball01.001']} skeleton={nodes.eyeballR.skeleton} />
        <skinnedMesh geometry={nodes.eyebrow.geometry} material={materials['chars_hair01.001']} skeleton={nodes.eyebrow.skeleton} />
        <skinnedMesh geometry={nodes.hair.geometry} material={materials['chars_hair03.001']} skeleton={nodes.hair.skeleton} />
        <skinnedMesh geometry={nodes.shoes.geometry} material={materials['chars_shoes03.001']} skeleton={nodes.shoes.skeleton} />
        <skinnedMesh geometry={nodes.socks.geometry} material={materials['chars_socks03.001']} skeleton={nodes.socks.skeleton} />
        <skinnedMesh geometry={nodes.teeth.geometry} material={materials['chars_body01.001']} skeleton={nodes.teeth.skeleton} />
        <skinnedMesh geometry={nodes.top_cloth.geometry} material={materials['chars_shirts04.001']} skeleton={nodes.top_cloth.skeleton} />
        <skinnedMesh name="eyelash" geometry={nodes.eyelash.geometry} material={materials['chars_eyelash11.001']} skeleton={nodes.eyelash.skeleton} morphTargetDictionary={nodes.eyelash.morphTargetDictionary} morphTargetInfluences={nodes.eyelash.morphTargetInfluences} />
        <skinnedMesh name="head" geometry={nodes.head.geometry} material={materials['chars_body04.001']} skeleton={nodes.head.skeleton} morphTargetDictionary={nodes.head.morphTargetDictionary} morphTargetInfluences={nodes.head.morphTargetInfluences} />
      </group>
    </group>
  )
}

useGLTF.preload('/base.glb')
